### PR TITLE
Implement HEALPix spatial and image arithmetic using PostgreSQL ranges and multiranges

### LINKED ISSUE #18: Fast union of regions
We need to be able to rapidly calculate the area or probability contained within the union of a set of ZTF fields. Each ZTF field is represented as a Region, which in turn is represented as rows in the Tiles table.

A Tile is a multi-resolution HEALPix pixel. HEALPix is a tree data structure. At the lowest level (level 0) it has 12 nodes; at all nodes beneath that, it is a quadtree. A multi-resolution HEALPix pixel has several equivalent representations:

1. A level (a nonnegative integer) and a pixel number between 0 and 12 (2^level)^2 - 1 inclusive
2. An interval (start and end) of pixel indices at a common very high level in the tree (level 29 for 64-bit data)

The Tile table currently uses the second representation. If there are N tiles that are each stored as lists sorted by starting pixel index, then finding the union of tiles simply amounts to a merge of N sorted lists followed by a de-duplication step.

Similar algorithms are commonly used for manipulating time interval data (e.g. https://lscsoft.docs.ligo.org/ligo-segments/) and genomics (https://pyranges.readthedocs.io/en/latest/autoapi/pyranges/pyranges/index.html).

This algorithm is not that complicated to implement in Python, but it needs to be done within the database. I have struggled to figure out how to do this in basic SQL. A solution might involve [CTEs](https://www.postgresql.org/docs/current/queries-with.html), [window functions](https://www.postgresql.org/docs/current/functions-window.html), or [procedural SQL](https://www.postgresql.org/docs/current/plpgsql.html).

### PR DESCRIPTION
**Pull request by lpsinger**
Fixes #18.

Note: merge #25 (or find some other fitting home for the cone search code) before merging this PR.

### CODE REVIEW

**Comment by lpsinger** [comment]
@mcoughlin, @bparazin, the last query in README.md is not working. I am stumped. Would you please take a look?

**Comment by lpsinger** [comment]
> @mcoughlin, @bparazin, the last query in README.md is not working. I am stumped. Would you please take a look?

Never mind, I figured it out.

**Comment by lpsinger** [comment]
This is ready for an initial review now.

**Comment by mcoughlin** [comment]
@lpsinger maybe you should make regions.Regions an option in addition to the current MOC + SkyCoord?

**Comment by lpsinger** [comment]
> @lpsinger maybe you should make regions.Regions an option in addition to the current MOC + SkyCoord?

Yes, this has occurred to me. I haven't done it yet because it will require recursively walking the Region. It might make the most sense to first contribute that functionality to mocpy and then use it here.

**Comment by lpsinger** [comment]
BTW, I'd especially like feedback on:

- The documentation and code samples
- Use of SQLAlchemy features
- Whether the queries are sufficiently idiomatic

**Comment by mcoughlin** [comment]
@lpsinger @acrellin Looks like the INT8RANGE stuff isn't compatible with the marshmallow_sqlalchemy used in SP.

  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/marshmallow_sqlalchemy/convert.py", line 252, in _get_field_class_for_data_type
    return self._get_field_class_for_data_type(data_type.impl)
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/marshmallow_sqlalchemy/convert.py", line 253, in _get_field_class_for_data_type
    raise ModelConversionError(
marshmallow_sqlalchemy.exceptions.ModelConversionError: Could not find field column of type <class 'sqlalchemy.dialects.postgresql.ranges.INT8RANGE'>.

Newer marshmallow_sqlalchemy's make breaking changes.

**Comment by lpsinger** [comment]
Can you exclude the INT8RANGE columns from marshmallow API responses? I can't think of any reason that we would ever need to return the INT8RANGE columns to the frontend.

**Comment by mcoughlin** [comment]
There are exclude flags, but not obvious how to make this work. I tried just adding "healpix" to the exclude list but didn't seem enough. I expect @acrellin or @stefanv know trivially.

**Comment by acrellin** [comment]
@mcoughlin Can you point me to exactly where you're seeing the marshmallow error and how to reproduce it locally? I'm happy to take a look.

**Comment by mcoughlin** [comment]
One request: how to determine what objects are within the 95% contour of the localizations.

**Comment by lpsinger** [comment]
> One request: how to determine what objects are within the 95% contour of the localizations.

Done.

**Comment by mcoughlin** [comment]
@lpsinger Running just this:

            cum_prob = sa.func.sum(
                LocalizationTile.probdensity * LocalizationTile.healpix.area
            ).over(order_by=LocalizationTile.probdensity.desc()).label('cum_prob')

            subquery1 = sa.select(LocalizationTile.probdensity, cum_prob)
 
Gives me:

    subquery1 = sa.select(LocalizationTile.probdensity, cum_prob)
  File "<string>", line 2, in select
  File "<string>", line 2, in __init__
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
    return fn(*args, **kwargs)
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/sql/selectable.py", line 3117, in __init__
    for c in columns:
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/sql/operators.py", line 432, in __getitem__
    return self.operate(getitem, index)
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 226, in operate
    return op(self.comparator, *other, **kwargs)
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/sql/operators.py", line 432, in __getitem__
    return self.operate(getitem, index)
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/orm/properties.py", line 367, in operate
    return op(self.__clause_element__(), *other, **kwargs)
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/sql/operators.py", line 432, in __getitem__
    return self.operate(getitem, index)
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 762, in operate
    return op(self.comparator, *other, **kwargs)
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/sql/operators.py", line 432, in __getitem__
    return self.operate(getitem, index)
  File "<string>", line 1, in <lambda>
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/sql/type_api.py", line 68, in operate
    return o[0](self.expr, op, *(other + o[1:]), **kwargs)
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/sql/default_comparator.py", line 237, in _getitem_impl
    _unsupported_impl(expr, op, other, **kw)
  File "/Users/mcoughlin/opt/anaconda3/envs/skyportal/lib/python3.8/site-packages/sqlalchemy/sql/default_comparator.py", line 241, in _unsupported_impl
    raise NotImplementedError(
NotImplementedError: Operator 'getitem' is not supported on this expression

Any ideas?

**Comment by mcoughlin** [comment]
@acrellin It looks like baselayer which pins to sqlachemy 1.3 era would need to be updated to 1.4 to use this. But I see issues like:

  File "/Users/mcoughlin/Code/ZTF/skyportal-branches/crossmatch2/skyportal/skyportal/models/schema.py", line 110, in setup_schema
    for class_ in _Base._decl_class_registry.values():
AttributeError: type object 'Base' has no attribute '_decl_class_registry'

**Comment by lpsinger** [comment]
> @acrellin It looks like baselayer which pins to sqlachemy 1.3 era would need to be updated to 1.4 to use this. But I see issues like:
> 
> File "/Users/mcoughlin/Code/ZTF/skyportal-branches/crossmatch2/skyportal/skyportal/models/schema.py", line 110, in setup_schema for class_ in _Base._decl_class_registry.values(): AttributeError: type object 'Base' has no attribute '_decl_class_registry'

So baselayer is requiring sqlalchemy 1.3 because it is poking at non-public API? Seems like a bug in baselayer.

**Comment by lpsinger** [comment]
> > @acrellin It looks like baselayer which pins to sqlachemy 1.3 era would need to be updated to 1.4 to use this. But I see issues like:
> > File "/Users/mcoughlin/Code/ZTF/skyportal-branches/crossmatch2/skyportal/skyportal/models/schema.py", line 110, in setup_schema for class_ in _Base._decl_class_registry.values(): AttributeError: type object 'Base' has no attribute '_decl_class_registry'
> 
> So baselayer is requiring sqlalchemy 1.3 because it is poking at non-public API? Seems like a bug in baselayer.

@acrellin, for fix, see https://stackoverflow.com/questions/11668355/sqlalchemy-get-model-from-table-name-this-may-imply-appending-some-function-to/66666783#66666783

**Review by acrellin — APPROVED** [review]
@lpsinger This looks good to me. I'd suggest not using the name `subquery` in the docs for expressions that aren't technically `subquery` instances, however.

**Comment by acrellin** [comment]
@lpsinger just now seeing your comments. Investigating a workaround for 1.4.

**Comment by acrellin** [comment]
And it's not baselayer, it's skyportal that's accessing that, and only for generating marshmallow schemas.

**Comment by acrellin** [comment]
I've implemented a workaround for our schema loader to work with 1.4, however there are bigger issues, particularly around breaking changes related to values constructs. We'll need to do a bit of refactoring before we can pin 1.4

**Comment by lpsinger** [comment]
> @lpsinger This looks good to me. I'd suggest not using the name `subquery` in the docs for expressions that aren't technically `subquery` instances, however.

Actually these are subqueries.

**Comment by lpsinger** [comment]
> I'd suggest not using the name `subquery` in the docs for expressions that aren't technically `subquery` instances, however.

Fixed.

**Comment by lpsinger** [comment]
> @lpsinger just now seeing your comments. Investigating a workaround for 1.4.

I am not sure if this package actually requires SQLAlchemy 1.4. It may simply be that my examples are in the "2.0" query style that debuted in SQLAlchemy 1.4. However 1.4 is supposed to have many performance enhancements over 1.3, so it's a good idea to migrate when possible.

How much effort do you think it will take to update skyportal to sqlalchemy 1.4? If it's a lot, then I could try adding an SQLAlchemy 1.3 test job to this package.

File: README.md [hunk 1]
```diff
@@ -1,16 +1,531 @@
...
+[hierarchical progressive surveys (HiPS)] used extensively in the [Aladin]
+astronomical information system. It is also used by LIGO and Virgo to store and
+communicate [gravitational-wave probability sky maps].
+
+HEALPix can be thought of as a tree. At the lowest resolution, level 0, HEALPix
+subdivides the sphere into 12 equal-area base tiles, assigned integer indicies
+0 through 11. At level 1, each of the 12 base tiles is subdivided into 4 tiles.
+Every subsequent level divides each of the preceding level's tiles into 4 new
+tiles. At a given level, each of the base pixels has been divided into
+_nside_ = 2<sup>_level_</sup> pixels on a side. Thus there are
```
Comment (stefanv) [inline README.md:76]: This is a very nice README!

I found the "on a side" text a bit confusing: maybe 4**level would be clearer to understand, given the preceding explanation?  Then also it simply becomes npix = 12 * 4**level below.

Comment (lpsinger) [reply README.md]: Should be fixed now. I changed it to:

> At a given level, each of the base pixels has been divided into 4<sup>_level_</sup> pixels (_nside_ = 2<sup>_level_</sup> pixels on each side). Thus there are _npix_ = 12×4<sup>_level_</sup> pixels at a given resolution, assigned integer indices from 0 through (_npix_-1).

because _nside_ is a really commonly used way to describe HEALPix resolution.

**Comment by lpsinger** [comment]
@mcoughlin, @acrellin, I adjusted the example queries so that they should work with SQLAlchemy 1.3. (Coincidentally, they also satisfy the future-proof "2.0" style.) Please try again.

**Comment by mcoughlin** [comment]
@lpsinger Seems to work well!

File: README.md [hunk 2]
```diff
@@ -1,16 +1,532 @@
...
+floating-point values attached to each tile. A multi-order refinement mesh from
+an example sky map is shown below, reproduced from [Singer & Price (2015)].
+
+![Example multi-order refinement mesh from a gravitational-wave probability sky map](https://emfollow.docs.ligo.org/userguide/_images/healpix-adaptive-mesh.svg)
+
+[Reinecke & Hivon (2015)][multi-order] introduced HEALPix interval sets as an
+alternative encoding of MOCs that enables fast and simple unions,
+intersections, and queries. In an interval set, each HEALPix tile is described
+by the interval of pixel indices at some very high resolution
+_level_<sub>max</sub> that are descendents of that tile. In an interval set, a
```
Comment (stefanv) [inline README.md:114]: So, just to confirm, descendent pixels are always labeled consecutively.

File: README.md [hunk 3]
```diff
@@ -1,16 +1,532 @@
...
+region is encoded as a disjoint collection of such intervals. A tile with a
+NESTED address given by (_level_, _ipix_) may be described as the half-open
+interval
+
+[_ipix_ 4<sup>_level_<sub>max</sub> - _level_</sup>,
+(_ipix_ + 1) 4<sup>_level_<sub>max</sub> - _level_</sup>).
+
+We use _level_<sub>max</sub> = 29 because this is the highest resolution at
+which pixel indices can be stored in a signed 64-bit integer. At this
```
Comment (stefanv) [inline README.md:123]: Why signed integers, when all indices are positive?

File: README.md [hunk 4]
```diff
@@ -1,16 +1,532 @@
...
+of galaxies in a catalog. Under the hood, it is just a `BIGINT`.
+
+Wherever you need to bind a Python value to a `healpix_alchemy.Point`, you may
+provide any one of the following:
+* an instance of [astropy.coordinates.SkyCoord]
+* a sequence of two [astropy.units.Quantity] instances with angle units, which
+  will be interpreted as the right ascension and declination of the point in
+  the [ICRS] frame
+* an integer representing the HEALPix NESTED index of the point at
+  _level_ = _level_<sub>max</sub>
```
Comment (stefanv) [inline README.md:150]: Is this always `level_29`, or is `level_max` somehow adjustable?

File: README.md [hunk 5]
```diff
@@ -1,16 +1,532 @@
...
+
+#### `healpix_alchemy.Tile`
+
+This class represents a HEALPix tile. A table containing a column of this type
+and a foreign key could store MOCs or gravitational-wave probability maps.
+Under the hood, it is just an `INT8RANGE`.
+
+Wherever you need to bind a Python value to a `healpix_alchemy.Tile`, you may
+provide any one of the following:
+* A single integer which will be interpreted as a the address of the tile in
```
Comment (stefanv) [inline README.md:160]:
```suggestion
* A single integer which will be interpreted as the address of the tile in
```

File: README.md [hunk 6]
```diff
@@ -1,16 +1,532 @@
...
+  the [UNIQ] HEALPix indexing scheme
+* A sequence of two integers, which will be interpreted as the lower and upper
+  bounds of the half-open pixel index interval at
+  _level_ = _level_<sub>max</sub>
+* A string like `'[1234,5678)'`
```
Comment (stefanv) [inline README.md:165]: Why is this supported? It's tricky to parse, and better represented as a tuple.

File: README.md [hunk 7]
```diff
@@ -1,16 +1,532 @@
...
+This class represents a HEALPix tile. A table containing a column of this type
+and a foreign key could store MOCs or gravitational-wave probability maps.
+Under the hood, it is just an `INT8RANGE`.
+
+Wherever you need to bind a Python value to a `healpix_alchemy.Tile`, you may
+provide any one of the following:
+* A single integer which will be interpreted as a the address of the tile in
+  the [UNIQ] HEALPix indexing scheme
+* A sequence of two integers, which will be interpreted as the lower and upper
+  bounds of the half-open pixel index interval at
```
Comment (stefanv) [inline README.md:163]: right-open? Otherwise need to specify which side is excluded or, perhaps easier, give an example:

```
* A sequence of two integers, `[M, N)`, which will be interpreted as the ...
```

File: healpix_alchemy/constants.py [hunk 8]
```diff
@@ -0,0 +1,18 @@
+from astropy.coordinates import ICRS
+from astropy import units as u
+from astropy_healpix import level_to_nside, HEALPix
+from mocpy import IntervalSet
+import sqlalchemy as sa
+
+LEVEL = IntervalSet.HPX_MAX_ORDER
```
Comment (stefanv) [inline healpix_alchemy/constants.py:7]: Let's hope these always stay constant :grimacing:

**Review by stefanv — APPROVED** [review]
:exploding_head: This is remarkably simple?!  I guess Postgres handles all the range arithmetic—beautiful.

I enjoyed reading the documentation; now I also know what's going on underneath the hood, so thanks for the lesson, Leo.

I left one or two tiny suggestions, but this is good to go.

**Review by mcoughlin — APPROVED** [review]
Between https://github.com/skyportal/skyportal/pull/2390 and https://github.com/skyportal/skyportal/pull/2420 I find the syntax enjoyable to work with and the examples quite clear. Thanks so much for all your work on this Leo.

**Review by acrellin — APPROVED** [review]

File: README.md [hunk 9]
```diff
@@ -1,16 +1,531 @@
...
+
+A HEALPix tile, a node in the HEALPix tree, is fully addressed by three pieces
+of information: the indexing scheme (RING or NESTED), the resolution level
+(_level_ or equivalently _nside_), and the pixel index (_ipix_, an integer
+between 0 and _npix_-1).
+
+The image below, reproduced from https://healpix.jpl.nasa.gov, illustrates the
+first 4 levels of refinement of a HEALPix grid.
+
+![The first four levels of HEALPix subdivision of the unit sphere](https://healpix.jpl.nasa.gov/images/healpixGridRefinement.jpg)
```
[the remark this answers is not in the document]
Comment (lpsinger) [reply README.md:90]: :-)

File: README.md (hunk 2 above)
Comment (lpsinger) [reply README.md:114]: Yes.

File: README.md (hunk 3 above)
Comment (lpsinger) [reply README.md:123]: Because several implementations of HEALPix (including chealpix, the official C language implementation) return int64 pixel indices and use -1 to indicate errors.

File: README.md (hunk 4 above)
Comment (lpsinger) [reply README.md:150]: You could set `level_max` to whatever value you want. But many practitioners (myself, the authors of the range set paper, the authors of mocpy) all use `level_max=29`.

File: README.md (hunk 5 above)
Comment (lpsinger) [reply README.md:160]: Fixed in 8ab41a87d63485b54b2bdf9a1ac9af1604f7ddc7.

File: README.md (hunk 7 above)
Comment (lpsinger) [reply README.md:163]: Fixed in 95064ae5e06bfe9e50162070212d3d6719fb3bdc.

File: healpix_alchemy/constants.py (hunk 8 above)
Comment (lpsinger) [reply healpix_alchemy/constants.py:7]: Can you think of a better name for this module, or a better place to put these values and objects? These are not meant to be part of the public API.

Comment (stefanv) [reply healpix_alchemy/constants.py:7]: How about renaming `constants` to `_constants`?
